# Dependencies for braille.$O:
braille.$O: $(SRC_DIR)/braille.c
braille.$O: $(BLD_TOP)config.h
braille.$O: $(SRC_TOP)prologue.h
braille.$O: $(SRC_TOP)Programs/log.h
braille.$O: $(SRC_TOP)Programs/timing.h
braille.$O: $(SRC_TOP)Programs/ascii.h
braille.$O: $(SRC_TOP)Programs/brl.h
braille.$O: $(BLD_TOP)Programs/brlapi_constants.h
braille.$O: $(SRC_TOP)Programs/brlapi_keycodes.h
braille.$O: $(SRC_TOP)Programs/brldefs.h
braille.$O: $(SRC_TOP)Programs/brltty.h
braille.$O: $(SRC_TOP)Programs/cmd.h
braille.$O: $(SRC_TOP)Programs/ctb.h
braille.$O: $(SRC_TOP)Programs/driver.h
braille.$O: $(SRC_TOP)Programs/ktb.h
braille.$O: $(SRC_TOP)Programs/ktbdefs.h
braille.$O: $(SRC_TOP)Programs/scr.h
braille.$O: $(SRC_TOP)Programs/ses.h
braille.$O: $(SRC_TOP)Programs/spk.h
braille.$O: $(SRC_TOP)Programs/brl_driver.h
braille.$O: $(SRC_TOP)Programs/statdefs.h
braille.$O: $(SRC_DIR)/brldefs-al.h
braille.$O: $(SRC_DIR)/braille.h
braille.$O: $(SRC_TOP)Programs/io_defs.h
braille.$O: $(SRC_TOP)Programs/io_serial.h
braille.$O: $(SRC_TOP)Programs/io_usb.h
braille.$O: $(SRC_TOP)Programs/io_bluetooth.h

