#!/bin/sh
###############################################################################
# BRLTTY - A background process providing access to the console screen (when in
#          text mode) for a blind person using a refreshable braille display.
#
# Copyright (C) 1995-2012 by The BRLTTY Developers.
#
# BRLTTY comes with ABSOLUTELY NO WARRANTY.
#
# This is free software, placed under the terms of the
# GNU General Public License, as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any
# later version. Please see the file LICENSE-GPL for details.
#
# Web Page: http://mielke.cc/brltty/
#
# This software is maintained by Dave Mielke <dave@mielke.cc>.
###############################################################################

prefix=""
exec_prefix="${prefix}"
datarootdir="${prefix}/usr/share"
bindir="${exec_prefix}/bin"
sbindir="${exec_prefix}/sbin"
libexecdir="${exec_prefix}/libexec"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
sharedstatedir="${prefix}/com"
localstatedir="${prefix}/var"
libdir="${exec_prefix}/lib"
includedir="${prefix}/usr/include"
oldincludedir="/usr/include"
infodir="${datarootdir}/info"
mandir="${datarootdir}/man"

BRLTTY_VERSION="4.3dev"
BRLTTY_EXECUTE_ROOT=""
BRLTTY_PROGRAM_DIRECTORY="${exec_prefix}/bin"
BRLTTY_DRIVERS_DIRECTORY="${exec_prefix}/lib/brltty"
BRLTTY_TABLES_DIRECTORY="${prefix}/etc/brltty"
BRLTTY_MANPAGE_DIRECTORY="${datarootdir}/man"
BRLTTY_INCLUDE_DIRECTORY="${prefix}/usr/include/brltty"

BRLAPI_VERSION="0.5"
BRLAPI_RELEASE="0.5.5"
BRLAPI_AUTH="brlapi.key"
